
'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Providers from "./rkt/providers";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (

<Providers>


<html lang="en">
      <body className={inter.className}>
      <ToastContainer 
   position="top-center"/>

{/* <Providers> */}
{children}
{/* </Providers> */}
   

       
        
        
        </body>
    </html>
    </Providers>
  );
}
